[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.16.0", features = ["v4"] }
shared = { path = "../shared" }
chrono = "0.4.40"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
clap = { version = "4.5.32", features = ["derive"] }
